"""baseline - matches current schema

Revision ID: 0377618c5c05
Revises: 
Create Date: 2026-08-01 01:31:14.579652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0377618c5c05'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('plan', sa.Text(), nullable=True))
    op.add_column('agent_steps', sa.Column('phase', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_steps', 'phase')
    op.drop_column('agent_runs', 'plan')
    # ### end Alembic commands ###
