"""add uploaded_files table

Revision ID: 17328b33685f
Revises: 4f7307d3171d
Create Date: 2026-08-02 11:18:36.957953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17328b33685f'
down_revision: Union[str, Sequence[str], None] = '4f7307d3171d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_files',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agent_steps', sa.Column('pending_action', sa.JSON(), nullable=True))
    op.add_column('agent_steps', sa.Column('resume_state', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_steps', 'resume_state')
    op.drop_column('agent_steps', 'pending_action')
    op.drop_table('uploaded_files')
    # ### end Alembic commands ###
