"""add observability fields

Revision ID: 4f7307d3171d
Revises: c766ec749542
Create Date: 2026-08-01 11:04:25.733676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7307d3171d'
down_revision: Union[str, Sequence[str], None] = 'c766ec749542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('agent_steps', sa.Column('duration_ms', sa.Integer(), nullable=True))
    op.add_column('agent_steps', sa.Column('is_error', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_steps', 'is_error')
    op.drop_column('agent_steps', 'duration_ms')
    op.drop_column('agent_runs', 'duration_ms')
    # ### end Alembic commands ###
