"""add multi-agent specialist column

Revision ID: b6be06afa826
Revises: 730b661243d3
Create Date: 2026-08-11 09:31:38.850521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6be06afa826'
down_revision: Union[str, Sequence[str], None] = '730b661243d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('specialist', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'specialist')
    op.drop_column('agent_runs', 'provider')
    # ### end Alembic commands ###
