"""add human approval fields

Revision ID: f97ff387f07b
Revises: 17328b33685f
Create Date: 2026-08-02 11:24:48.333787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f97ff387f07b'
down_revision: Union[str, Sequence[str], None] = '17328b33685f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('pending_action', sa.JSON(), nullable=True))
    op.add_column('agent_runs', sa.Column('resume_state', sa.JSON(), nullable=True))
    op.drop_column('agent_steps', 'resume_state')
    op.drop_column('agent_steps', 'pending_action')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_steps', sa.Column('pending_action', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('agent_steps', sa.Column('resume_state', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('agent_runs', 'resume_state')
    op.drop_column('agent_runs', 'pending_action')
    # ### end Alembic commands ###
